/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  // Set in the Webflow Cloud dashboard (Environment variables):
  CF_ACCOUNT_ID?: string;
  CF_API_TOKEN?: string;
}
